FROM ubuntu
RUN apt-get -y update
RUN apt-get update && apt-get install -y openssh-server python-pip python-dev build-essential libffi-dev libssl-dev 
RUN pip install --upgrade pip
RUN pip install --upgrade virtualenv
Run  pip install butterfly 
 
RUN adduser --disabled-password --gecos "" ritikavr
RUN echo 'root:ritikavr'| chpasswd
RUN echo 'ritikavr:ritikavr'|chpasswd
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]

